use_frameworks!

target 'ZWSNetwork_Example' do
  pod 'ZWSNetwork', :path => '../'

  target 'ZWSNetwork_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
